version: '3.7'


services:

    traefik:
        image: traefik
        command:
            - "--log.level=DEBUG"
            - "--api.debug=true"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        networks:
            - traefik-public
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        deploy:
            placement:
                constraints:
                    - node.role == manager

    hellod:
        build:
            dockerfile: ./hellod/Dockerfile
            context: .
        image: plant-recipescom_hellod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hellod.rule=PathPrefix(`/api/hellod`)"
        networks:
            - traefik-public

    hellodalpine:
        build:
            dockerfile: ./hellodalpine/Dockerfile
            context: .
        image: plant-recipescom_hellodalpine
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hellodalpine.rule=PathPrefix(`/api/hellodalpine`)"
        networks:
            - traefik-public

    hellojs:
        build:
            dockerfile: ./hellojs/Dockerfile
            context: .
        image: plant-recipescom_hellod
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hellojs.rule=PathPrefix(`/api/hellojs`)"
        networks:
            - traefik-public

    hellod-working-why:
        image: tam4s/hello-vibe-x86_64
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.hellod-working-why.rule=PathPrefix(`/api/hellod-working-why`)"
        networks:
            - traefik-public

networks:

    traefik-public:
        driver: overlay
